// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Producer.Domain
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class Payment : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""Payment"",""namespace"":""Producer.Domain"",""fields"":[{""name"":""Id"",""type"":""string""},{""name"":""Value"",""type"":""double""},{""name"":""Description"",""type"":[""null"",""string""]},{""name"":""SourceAccount"",""type"":""string""},{""name"":""TargetAccount"",""type"":""string""},{""name"":""Obs"",""type"":""string""}]}");
		private string _Id;
		private double _Value;
		private string _Description;
		private string _SourceAccount;
		private string _TargetAccount;
		private string _Obs;
		public virtual Schema Schema
		{
			get
			{
				return Payment._SCHEMA;
			}
		}
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				this._Id = value;
			}
		}
		public double Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				this._Value = value;
			}
		}
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				this._Description = value;
			}
		}
		public string SourceAccount
		{
			get
			{
				return this._SourceAccount;
			}
			set
			{
				this._SourceAccount = value;
			}
		}
		public string TargetAccount
		{
			get
			{
				return this._TargetAccount;
			}
			set
			{
				this._TargetAccount = value;
			}
		}
		public string Obs
		{
			get
			{
				return this._Obs;
			}
			set
			{
				this._Obs = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Id;
			case 1: return this.Value;
			case 2: return this.Description;
			case 3: return this.SourceAccount;
			case 4: return this.TargetAccount;
			case 5: return this.Obs;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Id = (System.String)fieldValue; break;
			case 1: this.Value = (System.Double)fieldValue; break;
			case 2: this.Description = (System.String)fieldValue; break;
			case 3: this.SourceAccount = (System.String)fieldValue; break;
			case 4: this.TargetAccount = (System.String)fieldValue; break;
			case 5: this.Obs = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
